---
- name: Check Docker is installed
  command: docker --version
  register: docker_version
  ignore_errors: yes

- name: Print Docker version
  debug:
    msg: "Docker version: {{ docker_version.stdout }}"

- name: Pull latest images
  command: docker-compose pull
  args:
    chdir: /opt/student-login-microservice

- name: Restart containers
  command: docker-compose restart
  args:
    chdir: /opt/student-login-microservice